apiVersion: v1
kind: Service
metadata:
  name: ticket-info
  namespace: ticket-system
spec:
  selector:
    app: ticket-info
  ports:
    - port: 8002
      targetPort: 8002
      nodePort: 30002
  type: NodePort
