apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: ticket-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
        - name: cart
          image: deidock/ticket-load-test-cart:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8003
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DATABASE_URL
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "otel-collector:4317"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8003
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8003
            initialDelaySeconds: 60
            periodSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
