apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: ticket-system
type: Opaque
stringData:
  POSTGRES_USER: devuser
  POSTGRES_PASSWORD: devpassword123
  POSTGRES_DB: ticketmanagerdb
  DATABASE_URL: postgresql://devuser:devpassword123@pgbouncer:5432/ticketmanagerdb
