apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-manager
  namespace: ticket-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket-manager
  template:
    metadata:
      labels:
        app: ticket-manager
    spec:
      containers:
        - name: ticket-manager
          image: deidock/ticket-load-test-ticket-manager:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DATABASE_URL
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "otel-collector:4317"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8001
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8001
            initialDelaySeconds: 60
            periodSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
