{
 "title": "Postgres",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "deadlocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(pg_stat_database_deadlocks{datname=\"ticketmanagerdb\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "pg_stat_database_blks_hit{datname=\"ticketmanagerdb\"}\r\n/\r\n(\r\n  pg_stat_database_blks_hit{datname=\"ticketmanagerdb\"}\r\n  +\r\n  pg_stat_database_blks_read{datname=\"ticketmanagerdb\"}\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rollbacks/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_rollback{datname=\"ticketmanagerdb\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{datname=\"ticketmanagerdb\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "100 * sum(pg_stat_activity_count) / scalar(pg_settings_max_connections)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum by (state) (pg_stat_activity_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Postgres up",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    { "expr": "pg_up", "legendFormat": "__auto" }
   ]
  }
 ]
}