apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: ticket-system
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "devuser", "-d", "ticketmanagerdb"]
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 5
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "devuser", "-d", "ticketmanagerdb"]
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 5
          args:
            - "-c"
            - "max_connections=250"
            - "-c"
            - "shared_buffers=2048MB"
            - "-c"
            - "synchronous_commit=off"
            - "-c"
            - "checkpoint_completion_target=0.9"
            - "-c"
            - "max_wal_size=2GB"
          resources:
            requests:
              cpu: 2500m
              memory: 6Gi
            limits:
              cpu: 2500m
              memory: 6Gi
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
