apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-generator
  namespace: ticket-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-generator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: user-generator
    spec:
      containers:
        - name: user-generator
          image: deidock/ticket-load-test-user-generator:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: sqlite-data
              mountPath: /app/db-data
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
      volumes:
        - name: sqlite-data
          persistentVolumeClaim:
            claimName: user-generator-pvc
