apiVersion: v1
kind: Secret
metadata:
  name: pgbouncer-exporter-secret
  namespace: ticket-system
type: Opaque
stringData:
  DATA_SOURCE_NAME: "postgresql://pgbouncer_monitor:monitorpassword123@pgbouncer:5432/pgbouncer?sslmode=disable"
